version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          apk add --no-cache openssl
      - run:
          name: Setup private and public keys
          command: |
              mkdir -p keys
              openssl genrsa -out keys/packager_key.rsa 2048
              openssl rsa -in keys/packager_key.rsa -pubout -out keys/packager_key.rsa.pub
      - run:
          name: Build application Docker image
          command: |
              ./gitobld build -rS base || true
